# Generated by Django 5.2.13 on 2026-05-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0002_clinic_therapistprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='template_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
