# Generated by Django 5.2.13 on 2026-05-13 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0004_exercisesession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercisesession',
            old_name='correct_answer',
            new_name='correct_answers',
        ),
        migrations.AlterField(
            model_name='exercisesession',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='therapy.exerciseassignment'),
        ),
    ]
